export const connectingWords = [
  'además',
  'ahora bien',
  'alguna vez',
  'algún día',
  'ambos',
  'ante todo',
  'apenas',
  'asimismo',
  'así',
  'aunque',
  'ayer',
  'bien',
  'cabe señalar',
  'como consecuencia',
  'como era de esperar',
  'como resultado',
  'como sabemos',
  'concluyendo',
  'consecuentemente',
  'consiguientemente',
  'contrariamente',
  'cuando',
  'dado que',
  'de acuerdo',
  'de hecho',
  'de por sí',
  'decididamente',
  'definitivamente',
  'desde el punto de vista',
  'desde entonces',
  'desde luego',
  'después',
  'después de todo',
  'en cambio',
  'en consecuencia',
  'en cuanto',
  'en efecto',
  'en especial',
  'en fin',
  'en general',
  'en la actualidad',
  'en la mayoría de los casos',
  'en lo personal',
  'en particular',
  'en primer lugar',
  'en realidad',
  'en resumen',
  'en segundo lugar',
  'enfrente',
  'entonces',
  'es decir',
  'es obvio',
  'excepto',
  'finalmente',
  'generalmente',
  'gracias a',
  'hasta',
  'hay que decir',
  'incluso',
  'indudablemente',
  'la verdad',
  'lógicamente',
  'me parece',
  'mientras',
  'misma',
  'mismamente',
  'mucho menos',
  'mucho más',
  'no obstante',
  'nos parece',
  'obviamente',
  'ocho',
  'por ello',
  'por eso',
  'por esta razón',
  'por lo demás',
  'por lo menos',
  'por lo que',
  'por lo tanto',
  'por lo visto',
  'por supuesto',
  'precisamente',
  'probablemente',
  'puesto que',
  'que',
  'radica en',
  'realmente',
  'resulta obvio',
  'resulta que',
  'rápidamente',
  'se podría esperar',
  'según',
  'siempre',
  'sin embargo',
  'sino',
  'sobre todo',
  'tal vez',
  'tanto',
  'tenemos que',
  'toda',
  'todas',
  'todas las',
  'todavía',
  'todos',
  'todos los',
  'totalmente',
  'tranquilamente',
  'un día',
  'una vez',
  'unas veces',
  'usualmente',
  'verdaderamente',
  'ya que',
]
